version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.52
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # UI
      - 14268:14268
      - 14250:14250
      - 4317:4317
      - 4318:4318
      - 9411:9411
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 54317:4317 # OTLP gRPC receiver
      - 54318:4318 # OTLP http receiver 推送数据的位置
      - 55679:55679 # zpages extension
